### ISSUE TITLE
Build fails on build 3.1-Release

### ISSUE THREAD

**Issue by acheron2013** [corinnekrych/swift-rpm#10]
Trying to build 3.1-RELEASE on Fedora 25 I get this error:

/root/rpmbuild/BUILD/build/buildbot_linux/swift-linux-x86_64/bin/swiftc -whole-module-optimization -emit-library -c /root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/Block.swift /root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/Data.swift /root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/Dispatch.swift /root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/IO.swift /root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/Private.swift /root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/Queue.swift /root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/Source.swift /root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/Time.swift /root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/Wrapper.swift \
-Xcc -fmodule-map-file=/root/rpmbuild/BUILD/swift-corelibs-libdispatch/dispatch/module.modulemap -I/root/rpmbuild/BUILD/swift-corelibs-libdispatch -Xcc -fblocks -O -module-name Dispatch -module-link-name dispatch \
-o /root/rpmbuild/BUILD/build/buildbot_linux/libdispatch-linux-x86_64/src/swift/swift_overlay.o -emit-module-path /root/rpmbuild/BUILD/build/buildbot_linux/libdispatch-linux-x86_64/src/swift/Dispatch.swiftmodule
**/root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/Time.swift:127:3: error: unknown attribute '_downgrade_exhaustivity_check'**
        @_downgrade_exhaustivity_check
         ^
**/root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/IO.swift:71:21: error: invalid redeclaration of 'init(type:path:oflag:mode:queue:cleanupHandler:)'**
        public convenience init?(
                           ^
**/root/rpmbuild/BUILD/swift-corelibs-libdispatch/src/swift/IO.swift:59:21: note: 'init(type:path:oflag:mode:queue:cleanupHandler:)' previously declared here**
        public convenience init(
                           ^
Makefile:1003: recipe for target '/root/rpmbuild/BUILD/build/buildbot_linux/libdispatch-linux-x86_64/src/swift/swift_overlay.o' failed
make[2]: *** [/root/rpmbuild/BUILD/build/buildbot_linux/libdispatch-linux-x86_64/src/swift/swift_overlay.o] Error 1
make[2]: Leaving directory '/root/rpmbuild/BUILD/build/buildbot_linux/libdispatch-linux-x86_64/src'
Makefile:545: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/rpmbuild/BUILD/build/buildbot_linux/libdispatch-linux-x86_64/src'
Makefile:453: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
./utils/build-script: fatal error: command terminated with a non-zero exit status 2, aborting
./utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
error: Bad exit status from /var/tmp/rpm-tmp.MGam51 (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.MGam51 (%build)

**Comment by tachoknight** [comment]
@acheron2013 Can you check out the current version and try again?

**Comment by acheron2013** [comment]
@tachoknight I just compiled this (4.0.2) on Fedora 27.  Worked perfectly.

**Comment by tachoknight** [comment]
Awesome! I'm going to close this issue then.
