### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by azmeuk** [corinnekrych/swift-rpm#5]
Hi. Thanks a lot for your work.
Did you consider submitting a package to Fedora?
That would be amazing.

**Comment by tachoknight** [comment]
Yes I started looking into that (I also have an update for NetHack 3.6 that I want to make available as an 'official' package), but I sort-of assumed something like Swift would have to come from someone more 'official', like Apple or someone with an @apple.com address, than some random person on the Internet. :) 

If that isn't the case, then yes, I'll happily go through the process of setting that up.

**Comment by azmeuk** [comment]
They seem to have a [mailing list](https://swift.org/community/#mailing-lists) and the [official swift repository](https://github.com/apple/swift) is hosted on github. Maybe it worth asking them if they would take care of it?
